OPT = -g3 -O0
LIB_SOURCES1 = tests.c canvas.c binui.c binui_3d.c binui_lisp_parser.c

LIB_SOURCES = $(addprefix src/, $(LIB_SOURCES1))
CC = gcc
TARGET = tests.so
LIB_OBJECTS =$(LIB_SOURCES:.c=.o)
LDFLAGS= -L. $(OPT) -shared -fPIC
LIBS= -lm  -licydb -ldl
ALL= $(TARGET)
CFLAGS = -I. -I./libmicroio/include -Isrc/ -Iinclude/ -std=gnu11 -c $(OPT) -Werror=implicit-function-declaration -Wformat=0 -D_GNU_SOURCE -fdiagnostics-color  -Wwrite-strings -msse4.2 -Werror=maybe-uninitialized -DUSE_VALGRIND -DDEBUG -fPIC -Wall -Wextra -Werror

$(TARGET): $(LIB_OBJECTS) ./iron/libiron.a
	$(CC) $(LDFLAGS) $(LIB_OBJECTS) ./iron/libiron.a $(LIBS) -o $@

all: $(ALL)

.c.o: $(HEADERS) $(LEVEL_CS)
	$(CC) $(CFLAGS) $< -o $@ -MMD -MF $@.depends

depend: h-depend
clean:
	rm -f $(LIB_OBJECTS) $(ALL) src/*.o.depends src/*.o src/level*.c src/*.shader.c 
.PHONY: test
test: $(TARGET)
	make -f makefile.compiler
	make -f makefile.test test

-include $(LIB_OBJECTS:.o=.o.depends)


