// This file is auto generated by icy-vector
#include "icydb.h"
typedef struct _binui_types{
  char ** column_names;
  char ** column_types;
  size_t * count;
  size_t * capacity;
  size_t * free_index_count;
  const size_t column_count;
  icy_mem * free_indexes;
  icy_mem * header;
  const size_t column_sizes[2];
  
  u8 * type;
  u8 * opcode_size;
  icy_mem * type_area;
  icy_mem * opcode_size_area;
}binui_types;

// a vector index.
typedef struct{
  size_t index;
}binui_types_index;

typedef struct{
  size_t index;
  size_t count;
}binui_types_indexes;

binui_types * binui_types_create(const char * optional_name);
binui_types_index binui_types_alloc(binui_types * table);
binui_types_indexes binui_types_alloc_sequence(binui_types * table, size_t count);
void binui_types_remove(binui_types * table, binui_types_index index);
void binui_types_remove_sequence(binui_types * table, binui_types_indexes * indexes);
void binui_types_clear(binui_types * table);
void binui_types_optimize(binui_types * table);
void binui_types_destroy(binui_types ** table);
