// This file is auto generated by icy-vector
#include "icydb.h"
typedef struct _f32_f32_vector{
  char ** column_names;
  char ** column_types;
  size_t * count;
  size_t * capacity;
  size_t * free_index_count;
  const size_t column_count;
  icy_mem * free_indexes;
  icy_mem * header;
  const size_t column_sizes[2];
  
  f32 * x;
  f32 * y;
  icy_mem * x_area;
  icy_mem * y_area;
}f32_f32_vector;

// a vector index.
typedef struct{
  size_t index;
}f32_f32_vector_index;

typedef struct{
  size_t index;
  size_t count;
}f32_f32_vector_indexes;

f32_f32_vector * f32_f32_vector_create(const char * optional_name);
f32_f32_vector_index f32_f32_vector_alloc(f32_f32_vector * table);
f32_f32_vector_indexes f32_f32_vector_alloc_sequence(f32_f32_vector * table, size_t count);
void f32_f32_vector_remove(f32_f32_vector * table, f32_f32_vector_index index);
void f32_f32_vector_remove_sequence(f32_f32_vector * table, f32_f32_vector_indexes * indexes);
void f32_f32_vector_clear(f32_f32_vector * table);
void f32_f32_vector_optimize(f32_f32_vector * table);
void f32_f32_vector_destroy(f32_f32_vector ** table);
