// This file is auto generated by icy-vector
#include "icydb.h"
typedef struct _string_table{
  char ** column_names;
  char ** column_types;
  size_t * count;
  size_t * capacity;
  size_t * free_index_count;
  const size_t column_count;
  icy_mem * free_indexes;
  icy_mem * header;
  const size_t column_sizes[1];
  
  u8 * data;
  icy_mem * data_area;
}string_table;

// a vector index.
typedef struct{
  size_t index;
}string_table_index;

typedef struct{
  size_t index;
  size_t count;
}string_table_indexes;

string_table * string_table_create(const char * optional_name);
string_table_index string_table_alloc(string_table * table);
string_table_indexes string_table_alloc_sequence(string_table * table, size_t count);
void string_table_remove(string_table * table, string_table_index index);
void string_table_remove_sequence(string_table * table, string_table_indexes * indexes);
void string_table_clear(string_table * table);
void string_table_optimize(string_table * table);
void string_table_destroy(string_table ** table);
