// This file is auto generated by icy-vector.
#ifndef TABLE_COMPILER_INDEX
#define TABLE_COMPILER_INDEX
#define array_element_size(array) sizeof(array[0])
#define array_count(array) (sizeof(array)/array_element_size(array))
#include "icydb.h"
#include <stdlib.h>
#endif

string_table * string_table_create(const char * optional_name){
  static const char * const column_names[] = {(char *)"data"};
  static const char * const column_types[] = {"u8"};

  string_table * instance = calloc(sizeof(string_table), 1);
  unsigned int sizes[] = {sizeof(u8)};
  
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  
  ((size_t *)&instance->column_count)[0] = 1;
  for(unsigned int i = 0; i < 1; i++)
    ((size_t *)instance->column_sizes)[i] = sizes[i];

  icy_vector_abs_init((icy_vector_abs * )instance, optional_name);

  return instance;
}


string_table_index string_table_alloc(string_table * table){
  icy_index idx = icy_vector_abs_alloc((icy_vector_abs *) table);
  string_table_index index;
  index.index = idx.index;
  return index;
}

string_table_indexes string_table_alloc_sequence(string_table * table, size_t count){
  icy_indexes idx = icy_vector_abs_alloc_sequence((icy_vector_abs *) table, count);
  string_table_indexes index;
  index.index = idx.index.index;
  index.count = count;
  return index;
}

void string_table_remove(string_table * table, string_table_index index){
  icy_index idx = {.index = index.index};
  icy_vector_abs_remove((icy_vector_abs *) table, idx);
}

void string_table_remove_sequence(string_table * table, string_table_indexes * indexes){
  icy_indexes idxs;
  idxs.index.index = (unsigned int)indexes->index;
  idxs.count = indexes->count;
  icy_vector_abs_remove_sequence((icy_vector_abs *) table, &idxs);
  memset(&indexes, 0, sizeof(indexes));
  
}
void string_table_clear(string_table * table){
  icy_vector_abs_clear((icy_vector_abs *) table);
}

void string_table_optimize(string_table * table){
  icy_vector_abs_optimize((icy_vector_abs *) table);
}
void string_table_destroy(string_table ** table){
  icy_vector_abs_destroy((icy_vector_abs **) table);
}
