// This file is auto generated by icy-table.
#include "icydb.h"
typedef struct _u64_pair_to_u64{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const u64_pair * k1, const u64_pair * k2);
  const size_t sizes[2];

  u64_pair * key;
  u64 * value;
  icy_mem * key_area;
  icy_mem * value_area;
}u64_pair_to_u64;

u64_pair_to_u64 * u64_pair_to_u64_create(const char * optional_name);
void u64_pair_to_u64_set(u64_pair_to_u64 * table, u64_pair key, u64 value);
void u64_pair_to_u64_insert(u64_pair_to_u64 * table, u64_pair * key, u64 * value, size_t count);
void u64_pair_to_u64_lookup(u64_pair_to_u64 * table, u64_pair * keys, size_t * out_indexes, size_t count);
void u64_pair_to_u64_remove(u64_pair_to_u64 * table, u64_pair * keys, size_t key_count);
void u64_pair_to_u64_clear(u64_pair_to_u64 * table);
void u64_pair_to_u64_unset(u64_pair_to_u64 * table, u64_pair key);
bool u64_pair_to_u64_try_get(u64_pair_to_u64 * table, u64_pair * key, u64 * value);
void u64_pair_to_u64_print(u64_pair_to_u64 * table);
size_t u64_pair_to_u64_iter(u64_pair_to_u64 * table, u64_pair * keys, size_t keycnt, u64_pair * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
